# Generated by Django 4.0.5 on 2022-07-08 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='myfriends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='None', max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('profile_pics', models.CharField(default='image.jpg', max_length=200)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('friends', models.ManyToManyField(blank=True, to='base.myfriends')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='personalmessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_body', models.CharField(max_length=2000)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('reciever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciever_id', to='base.profiles')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.profiles')),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.AddField(
            model_name='myfriends',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='base.profiles'),
        ),
        migrations.CreateModel(
            name='groupstable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='JUST CREATED!', max_length=200)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.profiles')),
                ('participants', models.ManyToManyField(blank=True, related_name='group_participants', to='base.profiles')),
            ],
        ),
        migrations.CreateModel(
            name='groupmessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_body', models.CharField(max_length=2000)),
                ('time_sent', models.DateTimeField(auto_now=True)),
                ('message_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.profiles')),
                ('owned_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.groupstable')),
            ],
            options={
                'ordering': ['-time_sent'],
            },
        ),
    ]
