# Generated by Django 4.0.5 on 2022-07-08 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_profiles_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='about',
            field=models.CharField(default='Hi', max_length=50),
        ),
        migrations.AddField(
            model_name='profiles',
            name='friends',
            field=models.ManyToManyField(blank=True, to='base.myfriends'),
        ),
    ]
