# Generated by Django 4.0.5 on 2022-07-08 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_friends_delete_myfriends_alter_profiles_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='friends',
        ),
        migrations.AddField(
            model_name='profiles',
            name='user_friends',
            field=models.ManyToManyField(blank=True, related_name='my_friends', to='base.friends'),
        ),
    ]
