# Generated by Django 4.0.5 on 2022-07-18 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_profiles_friends_profiles_user_friends'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personalmessages',
            options={'ordering': ['time']},
        ),
        migrations.RemoveField(
            model_name='profiles',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profiles',
            name='password',
        ),
        migrations.AddField(
            model_name='groupmessages',
            name='message_time_sent',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='personalmessages',
            name='message_time_sent',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='profile_pics',
            field=models.ImageField(default='image.jpg', upload_to='media'),
        ),
    ]
