# Generated by Django 4.0.5 on 2022-07-31 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_profiles_profile_pics'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personalmessages',
            options={'ordering': ['-time']},
        ),
    ]
